config/routes.rb
Refinery::Application.routes.draw do
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :admin_locales, :only => [:index, :edit, :update]
  end
end

app/controllers/admin/admin_locales_controller.rb
module Admin
  class AdminLocalesController < Admin::BaseController

    crudify :user,
          :order => 'username ASC',
          :title_attribute => :username,
          :xhr_paging => true

    def update
      locale = params[:user][:locale]
      @user.locale = locale if params[:user][:locale]
      if locale && @user.save
        redirect_to admin_admin_locales_path,
                    :notice => t('updated', :what => @user.username, :scope => 'refinery.crudify')
      else
        render :edit
      end
    end
  end
end

app/views/admin/admin_locales/_form.html.erb
<%= form_for @user, :url => admin_admin_locale_path(@user), :method => :put do |f| %>

  <%= render :partial => "/shared/admin/error_messages",
             :locals => {
               :object => @user,
               :include_object_name => true
             } %>

  <div class='field'>
    <%= f.label :locale %>
    <%= f.select :locale, options_for_select(Refinery::I18n.locales.map(&:reverse), @user.locale) %>
  </div>

  <%= render :partial => "/shared/admin/form_actions",
             :locals => {
               :f => f,
               :continue_editing => false,
               :hide_delete => true
             } %>
<% end %>

app/views/admin/admin_locales/_records.html.erb
<div class='pagination_container'>
  <%= render 'users' %>
</div>

app/views/admin/admin_locales/_user.html.erb
<li id="sortable_<%= user.id %>" class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <strong><%= user.username %></strong>
    <span class="preview">
      <%= t '.locale' %>: <%= user.locale ? Refinery::I18n.locales[user.locale.to_sym] : t('.default') %>
    </span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('application_edit.png'),
                edit_admin_admin_locale_path(user),
                :title => t('.edit') %>
  </span>
</li>

app/views/admin/admin_locales/_users.html.erb
<%= will_paginate @users %>
<ul>
  <%= render :partial => 'user', :collection => @users %>
</ul>

app/views/admin/admin_locales/edit.html.erb
<h1><%= User.model_name.human.capitalize %> <%= @user.username %></h1>
<%= render :partial => 'form' %>

app/views/admin/admin_locales/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>

app/views/refinery/admin_locales/admin/admin_locales/_user.html.erb
<li id="sortable_<%= user.id %>" class='clearfix record <%= cycle("on", "on-hover") %>'>
  <span class='title'>
    <strong><%= user.username %></strong>
    <span class="preview">
      <%= t '.locale' %>: <%= user.locale ? Refinery::I18n.locales[user.locale.to_sym] : t('.default') %>
    </span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag('application_edit.png'),
                refinery.edit_admin_locales_admin_admin_locale_path(user),
                :title => t('edit', :scope => 'refinery.admin.users') if current_refinery_user.can_edit?(user) %>
  </span>
</li>